name: sentiric

x-common-settings: &common-settings
  dns:
    - ${DISCOVERY_SERVICE_IPV4_ADDRESS:-10.88.5.1}
    - ${PRIMARY_DNS:-8.8.8.8}
    - ${SECONDARY_DNS:-1.1.1.1}
  dns_search:
    - ${DISCOVERY_DNS_SEARCH_DOMAIN:-service.sentiric.cloud}
  restart: always

networks:
  sentiric-net:
    driver: bridge
    name: sentiric-net
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-10.88.0.0/16}
          gateway: ${NETWORK_GATEWAY:-10.88.0.1}

# volumes:

services:

  sbc-service:
    <<: *common-settings

    image: ghcr.io/sentiric/sentiric-sbc-service:${TAG:-latest}

    build:
      context: ../sentiric-sbc-service
      dockerfile: Dockerfile

    environment:
      # --- Network
      # IP: 10.88.30.9  =>  Port Bloğu: 1309X
      - SBC_SERVICE_IPV4_ADDRESS=10.88.30.9
      - SBC_SERVICE_HTTP_PORT=13090
      - SBC_SERVICE_GRPC_PORT=13091
      - SBC_SERVICE_METRICS_PORT=13092
      - SBC_SERVICE_SIP_PORT=13094
      - SBC_SERVICE_HOST=sbc-service

      # --- Security
      - GRPC_TLS_CA_PATH=/sentiric-certificates/certs/ca.crt
      - SBC_SERVICE_CERT_PATH=/sentiric-certificates/certs/sbc-service-chain.crt
      - SBC_SERVICE_KEY_PATH=/sentiric-certificates/certs/sbc-service.key

    volumes:
      - "${CERTIFICATES_REPO_PATH:../sentiric-certificates}:/sentiric-certificates:ro"

    networks:
      sentiric-net:
        ipv4_address: ${SBC_SERVICE_IPV4_ADDRESS:-10.88.30.9}

    ports:
      - "${SBC_SERVICE_HTTP_PORT:-13090}:${SBC_SERVICE_HTTP_PORT:-13090}"
      - "${SBC_SERVICE_GRPC_PORT:-13091}:${SBC_SERVICE_GRPC_PORT:-13091}"
      - "${SBC_SERVICE_METRICS_PORT:-13092}:${SBC_SERVICE_METRICS_PORT:-13092}"
      - "${SBC_SERVICE_SIP_PORT:-13094}:${SBC_SERVICE_SIP_PORT:-13094}/udp"
      - "${SBC_SERVICE_SIP_PORT:-13094}:${SBC_SERVICE_SIP_PORT:-13094}/tcp"

    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "${SBC_SERVICE_GRPC_PORT:-13091}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
    # depends_on:     
    #   # Uygulama Servisleri -> Sadece 'started' olmaları yeterli     
    #   proxy-service: { condition: service_started }
